services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cqamcuggph6c73f6hucg-a.singapore-postgres.render.com:5432/fooddelivery_ut97
      SPRING_DATASOURCE_USERNAME: fooddelivery_ut97_user
      SPRING_DATASOURCE_PASSWORD: wHpEa9Z8gBjAro8gSArOaZguynS58WYs
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fooddelivery_ut97
      POSTGRES_USER: fooddelivery_ut97_user
      POSTGRES_PASSWORD: wHpEa9Z8gBjAro8gSArOaZguynS58WYs