services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_URL: jdbc:postgresql://dpg-cqamcuggph6c73f6hucg-a/fooddelivery_ut97
      POSTGRES_DB: fooddelivery_ut97
      POSTGRES_USER: fooddelivery_ut97_user
      POSTGRES_PASSWORD: wHpEa9Z8gBjAro8gSArOaZguynS58WYs

